### ISSUE TITLE
Charva

### ISSUE THREAD

**Issue by Scitz0** [drftpd-ng/drftpd3#1]
We should try to move away from the gui installer Charva to something pure java like Lanterna, https://github.com/mabe02/lanterna

Charva is dead since 2006 and require plattform specific libs. Also gui doesn't look correct in all terminals/systems.

If there are other alternatives please list them in this issue for evaluation.

**Comment by Scitz0** [comment]
It does not solve enhancement suggested in issue but as an alternativ to the gui console installer an automatic build option was added in 8eb97f4270d91cfb5140679b43d7462d5400f8af using the build.conf xml file generated by the gui installer (javabean of InstallerConfig) and with a fully automated switch(-a) added in 9aeae9666fbaefbe3e08f8b7fe272a1a6eabb7cb without user interaction.

**Comment by viktor-podzigun** [comment]
As an alternative, you can check [charva-lanterna](https://github.com/viktor-podzigun/charva-lanterna)

**Comment by zc0nf** [comment]
no more gui installer, maven only
