### ISSUE TITLE
Proxy BOT

### ISSUE THREAD

**Issue by zer0c0nf** [drftpd-ng/drftpd3#10]
Hello,

Can you make this mod?

irc bot with proxy supports, eg:
ip, port, user, password

Thx! :)

**Comment by surfaace** [comment]
please clarify if you mean like znc / psybnc support or to actually use sock4 or 5 proxys

**Comment by zer0c0nf** [comment]
If it is possible to do both, that would be great, but I was thinking more like a medium socks4 / 5 in order to pass through a proxy bot tor thus avoiding imdb queries etc or other with the source IP of the master :)

**Comment by zer0c0nf** [comment]
Okay after tests it is possible to safely use the BNC. I just thought that it is possible to integrate the tor support directly with a BNC (module).

**Comment by surfaace** [comment]
wont fix as there is no reason to use open socks proxys for IMDB requests, ip address of master is already showing when requesting PASV mode in during FTP transfers regardless of bouncers used
