### ISSUE TITLE
IMDB / TvMaze

### ISSUE THREAD

**Issue by zer0c0nf** [drftpd-ng/drftpd3#11]
Hello,

Can you fix :

I noticed that during an upload for a given release , for example test.MULTi.1080p.BluRay.x264 - BLABLA and once via the search !imdb test

2 HD are found :

IMDb -> Exist in :: SD : No, HD : Yes :: 2 match(es) found!

Is it to subfolder Sample? Why not just one?

Thank you.

**Comment by Scitz0** [comment]
Need more feedback on this one. Anyone else having issues?
Haven't been able to confirm this in own dev env.

**Comment by zer0c0nf** [comment]
DEBUG 2016-01-18 23:48:07,888 - [SiteBot Command Handler-132 - Waiting for commands] - Query: +parentPath:/X264/* +type:d +(+imdbtitle:the +imdbtitle:rings +imdbtitle:ring +imdbtitle:lord +imdbtitle:of +imdbtitle:fellowship) +imdbyear:[2001 TO 2001]
DEBUG 2016-01-18 23:48:07,901 - [SiteBot Command Handler-132 - Waiting for commands] - Query: +type:d +(+imdbtitle:the +imdbtitle:rings +imdbtitle:ring +imdbtitle:lord +imdbtitle:of +imdbtitle:fellowship) +imdbyear:[2001 TO 2001]
DEBUG 2016-01-18 23:48:07,902 - [SiteBot Command Handler-132 - Waiting for commands] - Query: +type:d +(+imdbtitle:the +imdbtitle:rings +imdbtitle:ring +imdbtitle:lord +imdbtitle:of +imdbtitle:fellowship) +imdbyear:[2001 TO 2001]
DEBUG 2016-01-18 23:48:07,904 - [SiteBot Command Handler-132 - Waiting for commands] - Query: +parentPath:/BLURAY/* +type:d +(+imdbtitle:the +imdbtitle:rings +imdbtitle:ring +imdbtitle:lord +imdbtitle:of +imdbtitle:fellowship) +imdbyear:[2001 TO 2001]
DEBUG 2016-01-18 23:48:07,904 - [SiteBot Command Handler-132 - Waiting for commands] - Query: +parentPath:/TV-SD-X264/* +type:d +(+imdbtitle:the +imdbtitle:rings +imdbtitle:ring +imdbtitle:lord +imdbtitle:of +imdbtitle:fellowship) +imdbyear:[2001 TO 2001]
DEBUG 2016-01-18 23:48:07,905 - [SiteBot Command Handler-132 - Waiting for commands] - Query: +parentPath:/TV-DVDRIP/* +type:d +(+imdbtitle:the +imdbtitle:rings +imdbtitle:ring +imdbtitle:lord +imdbtitle:of +imdbtitle:fellowship) +imdbyear:[2001 TO 2001]
DEBUG 2016-01-18 23:55:21,102 - [IndexMaintenanceThread] - Index was optimized successfully.

**Comment by zer0c0nf** [comment]
# Sections plugin should announce TvMAze info on races/pre, separate with ;
race.sections=X264;TV-HD-X264;TV-SD-X264;TV-HDRIP;TV-DVDRIP;BLURAY

# Search for release on site on imdb search, separate sections with ;
search.release=true
search.hd.sections=X264;TV-HD-X264;TV-HDRIP;BLURAY
search.sd.sections=TV-SD-X264;TV-DVDRIP
