### ISSUE TITLE
Duplicate files MOD

### ISSUE THREAD

**Issue by zer0c0nf** [drftpd-ng/drftpd3#13]
Hello,

I think it would be interesting, if it is not already possible, at least I do not think, enable the drftpd duplicate files (x1, x2, x3...) eg :

slave01 : file.r00, file.r01
slave02 : file.r00, file.r01
...

Thx!

**Comment by surfaace** [comment]
This wouldnt be good as with archiveplugin you might want to move files to more than 1 slave for "raid" like configuration. 
And there is a possibility to see what slaves that have the files by doing 'site list'
