### ISSUE TITLE
Bcrypt

### ISSUE THREAD

**Issue by zer0c0nf** [drftpd-ng/drftpd3#2]
Hello can you had bcrypt password encryption? :)

Thx

**Comment by zer0c0nf** [comment]
New user OK
site chpass and site password OK
HASH OK :)

Good job!

**Comment by surfaace** [comment]
fixed and merged to develop branch in https://github.com/drftpd-ng/drftpd3/commit/06f888a545a1ab2ca0d1370e53d0679e152dd976
