### ISSUE TITLE
Slave thrown offline during IOException in remerge causes salve to keep running

### ISSUE THREAD

**Issue by surfaace** [drftpd-ng/drftpd3#21]
Slave is thrown offline by master due to: org.drftpd.master.RemoteSlave - IOException during remerge java.io.FileNotFoundException: FileNotFound:

However the slave is still running and thinks its still connected

**Comment by Scitz0** [comment]
Fixed in d86b8a9bcc39de34fb99f57e5a3501c1ebf4998d
