### ISSUE TITLE
COLOR

### ISSUE THREAD

**Issue by zer0c0nf** [drftpd-ng/drftpd3#27]
Hello , is it possible that each section with color sections.conf file can put those same colors in other commands? for eg. !new etc.

Is it possible at the same time to dynamically manage colors annonce? Like : announce.conf ?

Thank you!

**Comment by Scitz0** [comment]
https://github.com/drftpd-ng/drftpd3/commit/da1e86035c674d0da8f4bf777727cfb6d9ee5a73 adds sectioncolor variable to a number of plugins where missing, could be more, open a new issue in that case.
