### ISSUE TITLE
problem on start new installation

### ISSUE THREAD

**Issue by bibidinu** [drftpd-ng/drftpd3#35]
hello guys i have this problem when try to start new installation someone can help me? 

Exception details.

Class: java.lang.Error
Message: failed creating plug-in life cycle handler instance org.java.plugin.drftpd.SynchronizedPluginLifecycleHandler

Stack trace:

org.java.plugin.standard.StandardObjectFactory.createLifecycleHandler(StandardObjectFactory.java:151)
org.java.plugin.standard.StandardObjectFactory.createManager(StandardObjectFactory.java:168)
org.java.plugin.ObjectFactory.createManager(ObjectFactory.java:271)
org.java.plugin.boot.DefaultApplicationInitializer.initApplication(DefaultApplicationInitializer.java:274)
org.java.plugin.boot.Boot.initApplication(Boot.java:538)
org.java.plugin.boot.Boot.boot(Boot.java:343)
org.java.plugin.boot.Boot.main(Boot.java:243)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:606)
org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
java.lang.Thread.run(Thread.java:745)

Caused by java.lang.ClassNotFoundException: org.java.plugin.drftpd.SynchronizedPluginLifecycleHandler

java.net.URLClassLoader$1.run(URLClassLoader.java:366)
java.net.URLClassLoader$1.run(URLClassLoader.java:355)
java.security.AccessController.doPrivileged(Native Method)
java.net.URLClassLoader.findClass(URLClassLoader.java:354)
java.lang.ClassLoader.loadClass(ClassLoader.java:425)
sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
java.lang.ClassLoader.loadClass(ClassLoader.java:358)
org.java.plugin.standard.StandardObjectFactory.createClassInstance(StandardObjectFactory.java:76)
org.java.plugin.standard.StandardObjectFactory.createLifecycleHandler(StandardObjectFactory.java:147)
org.java.plugin.standard.StandardObjectFactory.createManager(StandardObjectFactory.java:168)
org.java.plugin.ObjectFactory.createManager(ObjectFactory.java:271)
org.java.plugin.boot.DefaultApplicationInitializer.initApplication(DefaultApplicationInitializer.java:274)
org.java.plugin.boot.Boot.initApplication(Boot.java:538)
org.java.plugin.boot.Boot.boot(Boot.java:343)
org.java.plugin.boot.Boot.main(Boot.java:243)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:606)
org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
java.lang.Thread.run(Thread.java:745)

**Comment by zer0c0nf** [comment]
bibidinu, same problem?

**Comment by Scitz0** [comment]
No other reports of issues like this, most likely all necessary installation steps are not followed.
