### ISSUE TITLE
Archive plugin unable to find localpath

### ISSUE THREAD

**Issue by surfaace** [drftpd-ng/drftpd3#5]
Archive plugin reads case sensitive on when trying to find a file on local fs in atleast linux, if the file is not found the slave goes offline with error message below.
Issue mostly occurs when using combination .todirectorytype=rls:${rls}/Season.${season}

[OFFLINE] slave came offline with reason /path/file wasn't found in any root.

**Comment by daromer2** [comment]
Can also be noted that when it fails the slave goes offline but the process is still running in background on the server.
