### ISSUE TITLE
mediainfo issue and .mp4,.mov,.wmv support

### ISSUE THREAD

**Issue by zer0c0nf** [drftpd-ng/drftpd3#60]
Hello,

Ive issue with mediainfo about a_Bit variable : 

-AUDIO- Unknown : AAC @ 122kb/s a_Bit rate mode : 48.0kHz : 2channels

I think its Format profile now?

And, can you make .mp4,.mov,.wmv support?

Thx

**Comment by Scitz0** [comment]
As mediainfo plugin relies on the external application mediainfo the output available is restricted to what it outputs. "Bit rate" & "Bit rate mode" doesn't seem to be available for AAC audio, nothing I can do about that. Remove it from theme output.

As for the file type support please check configuration, it clearly shows how to add more extensions. Then just add the correct lines to theme output.
