### ISSUE TITLE
LinkManager NFOMISSING an SFVMISSING have error or bug

### ISSUE THREAD

**Issue by nostromo1st** [drftpd-ng/drftpd3#62]
Yesterday i have download the last develop release and upgrade mine.
i want to setup NFOMISSING and SFV MISSING 
my dirs are like this: /SECTIONS/Dirtest/Dirtest.S01/Dirtest.S01E01

I just want a no-sfv or no-sfv for Dirtest.S01E01

my code is:

>1.type=NFOMISSING
1.dirname=/_NO_NFO
1.section=*
1.exclude=^/(.*)/(.*)/(?i)(((cd|dvd|dis[ck])[1-9])|sample|subs|rarfix)$
1.sectionexclude=^(?i)(pre|staff|speedtests)$
1.deleteon=*
1.linkname=(no-nfo)-${dirname}
1.addparentdir=^(?i)(((cd|dvd|dis[ck])[1-9])|sample|subs|rarfix)$

is here any problem ? or perhaps a bug ? can you looking for pease

Thanks in advance, 
Regards, 
Nostromo.

**Comment by epochyx** [comment]
I'm guessing you found a solution, and that is outdated. Feel free to resubmit an issue with more detailed infos or using the bug report template if this is still an issue for you.
