### ISSUE TITLE
SFV

### ISSUE THREAD

**Issue by zc0nf** [drftpd-ng/drftpd3#68]
Hello,

Problem 1:
Very often it is impossible to complete a release the first time, it stops at 98% and we are forced to restart a transfer of the missing file.

[http://paste.drftpd.org/1053/](http://paste.drftpd.org/1053/) and [http://paste.drftpd.org/1054/](http://paste.drftpd.org/1054/)

Problem 2:
When trying to complete a release with a missing file, the irc bot does not announce that the release is complete, it just announces "FIRST" and it does not take the number of missing files, it will announce that all files with their size must be transferred "Expecting 4.7GB in 94 files."

[http://paste.drftpd.org/1054/](http://paste.drftpd.org/1054/)

Problem 3:
The drftpd displays to the autonuke that the rls is incomplete when it is complete, so it is necessary to make a site rescan on the directory of the rls in order to be able to correctly raise the correct size of the file seen as not transferred. For example, on a rls containing 71 files, drftpd will display via ftp, that there are only 70 files transferred, which is false of course. The method is to make a site rescan, wait until the file does not display the correct size by ftp but yet the correct size on the hard disk is correct and then to erase via a delqueue of the autonuke that the rls is incomplete. This problem is very troublesome and leads to false positives with the autonuke.

Thank you for your help,

zer0c0nf

**Comment by epochyx** [comment]
Please validate the bug still happens using the latest version, and report the java version and OS used. Closing this to have one problem / issue and more detailed information.
