### ISSUE TITLE
SSLv3 - dh key too small

### ISSUE THREAD

**Issue by janno007** [drftpd-ng/drftpd3#78]
when trying to connect from RushFTP to a drFTPd3 server via SSL I get the error:
---
error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small 
Network subsystem is unusable(10091)
---
Is this a FTP client issue or a drFTPd issue or a combo?
(I can connect fine from the latest FlashFXP client)

Thanks!

**Comment by donmagic1** [comment]
could be rushftp outdated

**Comment by janno007** [comment]
I was able to find a solution although I wasn't able to pinpoint the exact problem:

Solution:
-> Update JAVA client on the drFTPd3 machine from v1.6 to v1.7

FlashFXP v5.4.0 with the 2017 SSL libs works fine with drFTPd3 and JAVA 1.6 / 1.7
FTPRush v1.1.3 Unicode with the 2014 SSL libs works fine with drFTPd3 and JAVA 1.6
FTPRush v1.1.3 Unicode with the 2017 SSL libs does not work on drFTPd3 and JAVA 1.6
FTPRush v1.1.3 Unicode with the 2017 SSL libs works fine with drFTPd3 and JAVA 1.7

So it must be something in the combination with FTPRush + 2017 SSL libs + drFTPd + JAVA 1.6
But anyhow, it works fine again, so I'm happy, perhaps if anyone knows the exact issue, or has a pretty good idea, please let me know :)  Thanks!

**Comment by zer0c0nf** [comment]
Thanks, it is advisable to use the develop version which is the most up-to-date, with java 8 and ssl libraries updated also for the FTP client
