### ISSUE TITLE
SpeedTest URL

### ISSUE THREAD

**Issue by zer0c0nf** [drftpd-ng/drftpd3#8]
Hello,

Is it possible to create a mod or improve the mod in speedtest to specify a url like iso or bin file.

!speedtest slave01
slave01 : 50MB/S blabla..
!speedtest allslaves
slave01 : 50MB/s blabla..
slave02...
total : blabla...

Thus allowing to create a bandwidth test for slave and for all slaves.

Thx

**Comment by zer0c0nf** [comment]
<@owner> !speedtest SLAVE01 -list
<drftpd> Failed getting SLAVE01 location from http://www.speedtest.net/ 12·
<drftpd> SLAVE01 :: Server -> Bluecloud Networks Ltd (Ghana) [617,57 km] (6213) 12·
<drftpd> SLAVE01 :: Server -> TOGO TELECOM (Togo) [693,39 km] (7057) 12·
<drftpd> SLAVE01 :: Server -> MTN COTE D'IVOIRE (Ivory Coast) [743,10 km] (6198) 12·
<drftpd> SLAVE01 :: Server -> CST- Companhia Santomense de Telecomunicacoes (Sao Tome and Principe) [749,59 km] (4236) 12·
<drftpd> SLAVE01 :: Server -> Cobranet Ltd (Nigeria) [809,48 km] (1939) 12·

<@owner> !speedtest SLAVE0* 3917
<drftpd> SLAVE0* not found, check spelling! 12·
<@owner> !speedtest SLAVE* 3917
<drftpd> SLAVE* not found, check spelling! 12·
<@owner> !speedtest SLAVE01,SLAVE02 3917
<drftpd> SLAVE01,SLAVE02 not found, check spelling! 12·
<@owner> !speedtest SLAVE01;SLAVE02 3917
<drftpd> SLAVE01;SLAVE02 not found, check spelling! 12·
<@owner> !speedtest SLAVE01 SLAVE02 3917
<drftpd> SPEEDTEST [<slavename> [-list] [<test server id>]] [-refresh] 12·

<@owner> !speedtest * 3917
<drftpd> SPEEDTEST [<slavename> [-list] [<test server id>]] [-refresh] 12·

Thx for ur work! :+1:

**Comment by zer0c0nf** [comment]
[21:40] <+cactus> jvm 1    | Exception in thread "DrFTPD-Bot" org.drftpd.exceptions.FatalException: org.drftpd.exceptions.FatalException: speedtest is already mapped on line 1184
[21:40] <+cactus> jvm 1    |      at org.drftpd.GlobalContext.loadCommandConfig(GlobalContext.java:414)
[21:40] <+cactus> jvm 1    |      at org.drftpd.plugins.sitebot.SiteBot.loadCommands(SiteBot.java:2817)
[21:40] <+cactus> jvm 1    |      at org.drftpd.plugins.sitebot.SiteBot.run(SiteBot.java:196)
[21:40] <+cactus> jvm 1    |      at java.lang.Thread.run(Thread.java:745)
[21:40] <+cactus> jvm 1    | Caused by: org.drftpd.exceptions.FatalException: speedtest is already mapped on line 1184
[21:40] <+cactus> jvm 1    |      at org.drftpd.GlobalContext.loadCommandConfig(GlobalContext.java:395)
[21:40] <+cactus> jvm 1    |      ... 3 more

ERROR 2016-01-17 21:40:32,791 [DrFTPD-Bot] org.drftpd.GlobalContext  - Error reading line 1184 in conf/plugins/irc/irccommands.conf

speedtest {
plugin org.drftpd.commands.speedtest
class SpeedTest
method doSITE_SPEEDTEST
perms =siteop
help Run a speedtest on slave against speedtest.net test servers, * for all slaves
help.specific ${command} [<slavename> [-list] [<test server id>]] [-refresh]
help.specific -refresh force an update of speedtest.net server list
help.specific -list option in conjunction with slave name lists closests servers to slave location based on its IP
help.specific An optional test server id can be specified to force test server
input all
output source
}

speedtest {
plugin org.drftpd.commands.speedtest.net
class SpeedTest
method doSITE_SPEEDTEST
perms =siteop
help Run a speedtest on slave against speedtest.net test servers, * for all slaves
help.specific ${command} [<slavename> [-list] [<test server id>]] [-refresh]
help.specific -refresh force an update of speedtest.net server list
help.specific -list option in conjunction with slave name lists closests servers to slave location based on its IP
help.specific An optional test server id can be specified to force test server
input all
output source
}

**Comment by surfaace** [comment]
Above comment was local command duplicate in his irccommands.conf, no issue

**Comment by Scitz0** [comment]
Plugin implemented by 361120c
